### ISSUE TITLE
Public Test Server Roadmap

### ISSUE THREAD

**Issue by InusualZ** [sepalani/MH3SP#44]
# Public Test Server Roadmap

This would be a list of feature/bug that we need to implement/fix in order to have the first public test server.

- [x] Allow password to be set in circle ( #45 )
- [x] Re-transmit circle's members when the player collection change (#65)
  - [X] When a player get kick its not reflected on the quest board (#47)
  - [x] When a player disconnect its not reflected on the quest board (#28, #65)
- [ ] Correctly show at which layer stage the player is in (city, quest ready, quest)
  - [x] In the city board ( #46 )
  - [ ] In the friend list
- [x] When circle leader disconnect while in game, transfer leadership to another player. (#65 )
- [x] Handle correctly when a player lost connection (#28 )
  - [x] Kick them out of circle if in one (#65 )
  - [x] Kick them out of city if in one
  - [x] Kick them out of the gate
- [x] Replace various assert for client facing error messages
  - [x] When there are [no empty circle](https://github.com/sepalani/MH3SP/blob/74bfd4a9c22852304f0b4f3beb58b56835af818a/fmp_server.py#L404=) (#54 )
  - [x] When the [quest id is invalid](https://github.com/sepalani/MH3SP/blob/74bfd4a9c22852304f0b4f3beb58b56835af818a/fmp_server.py#L433=) (#54 )
  - [x] When the [circle doesn't exist](https://github.com/sepalani/MH3SP/blob/74bfd4a9c22852304f0b4f3beb58b56835af818a/fmp_server.py#L531=) (#54 )
  - [x] When the circle's [leader is not found](https://github.com/sepalani/MH3SP/blob/74bfd4a9c22852304f0b4f3beb58b56835af818a/fmp_server.py#L621=) (#54 )
- [x] Circle showing the player's weapon type (#52 )
- [x] Properly synchronize players armor when someone change them inside the city (#92)
- [x] Even though all party members (in a quest) are ready, the game would still say that their not. (#65)
- [ ] Friend List ( #48 )
- [ ] Block List
- [ ] Friend -> Warp To
- [ ] Changing from gate to gate
- [ ] Announcement and User Agreement Configurable
- [x] Poll sockets (#51 )
  - Instead of creating a thread for each accepted connection (socket) poll them in a single thread (And maybe distribute their work between multiple thread)
- [ ] Update Patching Methods
- [ ] Update Setup Guides

##  **This is list is not final, we may add things to it while we implement/fix features/bug in the list**

Once we complete this list, we would be conducting a public test server. This test server would have a limited capacity 20-40 people (whitelist). There would be a hole lot of more feature to implement after this public test server.

**Comment by InusualZ** [comment]
I think this can be closed :)
